// TurboQuant: Near-optimal KV cache compression for prompt cache.
// Based on arXiv:2504.19874 (ICLR 2026), Algorithm 1 (TurboQuant_MSE only).
//
// Operates on serialized KV state buffers (std::vector<uint8_t>) produced by
// llama_state_seq_get_data_ext(). Compresses per-layer K/V tensor data using
// random orthogonal rotation + Beta-distribution optimal scalar quantization.
//
// Self-contained: codebook tables hardcoded, rotation matrix generated at
// runtime via Gram-Schmidt QR. No external dependencies.

#include "server-turboquant.h"
#include "server-common.h"

#include "ggml.h"

#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstring>
#include <mutex>
#include <random>
#include <vector>

// ============================================================================
// Codebook tables — auto-generated by training/scripts/generate_turboquant_tables.py
// ============================================================================

// dim=128, bits=3, n_centroids=8
static constexpr float tq_boundaries_d128_b3[] = {-0.1020110649f, -0.0599153074f, -0.0283246971f, 0.0000000000f, 0.0283246971f, 0.0599153074f, 0.1020110649f};
static constexpr float tq_centroids_d128_b3[] = {-0.1454646786f, -0.0794742280f, -0.0436625398f, -0.0140443538f, 0.0140443538f, 0.0436625398f, 0.0794742280f, 0.1454646786f};

// dim=128, bits=4, n_centroids=16
static constexpr float tq_boundaries_d128_b4[] = {-0.1357670400f, -0.1020110649f, -0.0787540372f, -0.0599153074f, -0.0434368308f, -0.0283246971f, -0.0139858868f, 0.0000000000f, 0.0139858868f, 0.0283246971f, 0.0434368308f, 0.0599153074f, 0.0787540372f, 0.1020110649f, 0.1357670400f};
static constexpr float tq_centroids_d128_b4[] = {-0.1734592013f, -0.1174705572f, -0.0898708558f, -0.0690776014f, -0.0515296984f, -0.0357953815f, -0.0211100023f, -0.0069787054f, 0.0069787054f, 0.0211100023f, 0.0357953815f, 0.0515296984f, 0.0690776014f, 0.0898708558f, 0.1174705572f, 0.1734592013f};

// dim=256, bits=3, n_centroids=8
static constexpr float tq_boundaries_d256_b3[] = {-0.0720146692f, -0.0422607232f, -0.0199715507f, 0.0000000000f, 0.0199715507f, 0.0422607232f, 0.0720146692f};
static constexpr float tq_centroids_d256_b3[] = {-0.1028929378f, -0.0560788673f, -0.0307914098f, -0.0099020737f, 0.0099020737f, 0.0307914098f, 0.0560788673f, 0.1028929378f};

// dim=256, bits=4, n_centroids=16
static constexpr float tq_boundaries_d256_b4[] = {-0.0959426195f, -0.0720146692f, -0.0555667861f, -0.0422607232f, -0.0306311979f, -0.0199715507f, -0.0098606001f, 0.0000000000f, 0.0098606001f, 0.0199715507f, 0.0306311979f, 0.0422607232f, 0.0555667861f, 0.0720146692f, 0.0959426195f};
static constexpr float tq_centroids_d256_b4[] = {-0.1228194336f, -0.0829670309f, -0.0634266527f, -0.0487310828f, -0.0363420360f, -0.0252407839f, -0.0148839465f, -0.0049202011f, 0.0049202011f, 0.0148839465f, 0.0252407839f, 0.0363420360f, 0.0487310828f, 0.0634266527f, 0.0829670309f, 0.1228194336f};

// dim=512, bits=3, n_centroids=8
static constexpr float tq_boundaries_d512_b3[] = {-0.0508803815f, -0.0298456205f, -0.0141019721f, 0.0000000000f, 0.0141019721f, 0.0298456205f, 0.0508803815f};
static constexpr float tq_centroids_d512_b3[] = {-0.0727675219f, -0.0396122104f, -0.0217437446f, -0.0069917077f, 0.0069917077f, 0.0217437446f, 0.0396122104f, 0.0727675219f};

// dim=512, bits=4, n_centroids=16
static constexpr float tq_boundaries_d512_b4[] = {-0.0678205128f, -0.0508803815f, -0.0392491272f, -0.0298456205f, -0.0216302453f, -0.0141019721f, -0.0069623360f, 0.0000000000f, 0.0069623360f, 0.0141019721f, 0.0216302453f, 0.0298456205f, 0.0392491272f, 0.0508803815f, 0.0678205128f};
static constexpr float tq_centroids_d512_b4[] = {-0.0869037777f, -0.0586321190f, -0.0448065279f, -0.0344178934f, -0.0256642994f, -0.0178231899f, -0.0105093994f, -0.0034740161f, 0.0034740161f, 0.0105093994f, 0.0178231899f, 0.0256642994f, 0.0344178934f, 0.0448065279f, 0.0586321190f, 0.0869037777f};

static const float * tq_get_boundaries(uint32_t dim, uint8_t bits) {
    if (dim == 128 && bits == 3) return tq_boundaries_d128_b3;
    if (dim == 128 && bits == 4) return tq_boundaries_d128_b4;
    if (dim == 256 && bits == 3) return tq_boundaries_d256_b3;
    if (dim == 256 && bits == 4) return tq_boundaries_d256_b4;
    if (dim == 512 && bits == 3) return tq_boundaries_d512_b3;
    if (dim == 512 && bits == 4) return tq_boundaries_d512_b4;
    return nullptr;
}

static const float * tq_get_centroids(uint32_t dim, uint8_t bits) {
    if (dim == 128 && bits == 3) return tq_centroids_d128_b3;
    if (dim == 128 && bits == 4) return tq_centroids_d128_b4;
    if (dim == 256 && bits == 3) return tq_centroids_d256_b3;
    if (dim == 256 && bits == 4) return tq_centroids_d256_b4;
    if (dim == 512 && bits == 3) return tq_centroids_d512_b3;
    if (dim == 512 && bits == 4) return tq_centroids_d512_b4;
    return nullptr;
}

// ============================================================================
// Rotation matrix — Gram-Schmidt QR of deterministic Gaussian matrix
// ============================================================================

struct tq_rotation {
    uint32_t dim;
    std::vector<float> Q; // (dim, dim) row-major orthogonal matrix

    tq_rotation(uint32_t dim, uint32_t seed) : dim(dim), Q(dim * dim) {
        // Generate random Gaussian matrix
        std::mt19937 rng(seed);
        std::normal_distribution<float> dist(0.0f, 1.0f);

        std::vector<float> A(dim * dim);
        for (size_t i = 0; i < dim * dim; ++i) {
            A[i] = dist(rng);
        }

        // Modified Gram-Schmidt QR decomposition
        // Q = orthogonalized columns of A
        for (uint32_t j = 0; j < dim; ++j) {
            // Copy column j of A into Q
            for (uint32_t i = 0; i < dim; ++i) {
                Q[i * dim + j] = A[i * dim + j];
            }

            // Orthogonalize against previous columns
            for (uint32_t k = 0; k < j; ++k) {
                float dot = 0.0f;
                for (uint32_t i = 0; i < dim; ++i) {
                    dot += Q[i * dim + k] * Q[i * dim + j];
                }
                for (uint32_t i = 0; i < dim; ++i) {
                    Q[i * dim + j] -= dot * Q[i * dim + k];
                }
            }

            // Normalize
            float norm = 0.0f;
            for (uint32_t i = 0; i < dim; ++i) {
                norm += Q[i * dim + j] * Q[i * dim + j];
            }
            norm = std::sqrt(norm);
            if (norm > 1e-10f) {
                for (uint32_t i = 0; i < dim; ++i) {
                    Q[i * dim + j] /= norm;
                }
            }
        }

        // Ensure proper rotation (det = +1): flip sign of columns where R diagonal is negative
        // R[j,j] = dot(original_col_j, Q_col_j)
        for (uint32_t j = 0; j < dim; ++j) {
            float r_jj = 0.0f;
            for (uint32_t i = 0; i < dim; ++i) {
                r_jj += A[i * dim + j] * Q[i * dim + j];
            }
            if (r_jj < 0.0f) {
                for (uint32_t i = 0; i < dim; ++i) {
                    Q[i * dim + j] = -Q[i * dim + j];
                }
            }
        }
    }

    // y = x @ Q^T  (rotate forward: multiply by transpose)
    // x: (dim,), y: (dim,)
    void rotate_forward(const float * x, float * y) const {
        for (uint32_t j = 0; j < dim; ++j) {
            float sum = 0.0f;
            // Q^T[j, i] = Q[i, j] (column j of Q)
            for (uint32_t i = 0; i < dim; ++i) {
                sum += x[i] * Q[i * dim + j];
            }
            y[j] = sum;
        }
    }

    // y = x @ Q  (rotate backward: multiply by Q)
    // x: (dim,), y: (dim,)
    void rotate_backward(const float * x, float * y) const {
        for (uint32_t j = 0; j < dim; ++j) {
            float sum = 0.0f;
            // Q[j, i] = row j of Q
            for (uint32_t i = 0; i < dim; ++i) {
                sum += x[i] * Q[j * dim + i];
            }
            y[j] = sum;
        }
    }
};

// Cache rotation matrices by (dim, seed)
static std::mutex s_rotation_mutex;
static std::vector<tq_rotation> s_rotations;

static const tq_rotation & get_rotation(uint32_t dim, uint32_t seed) {
    std::lock_guard<std::mutex> lock(s_rotation_mutex);
    for (const auto & r : s_rotations) {
        if (r.dim == dim) {
            return r;
        }
    }
    s_rotations.emplace_back(dim, seed);
    return s_rotations.back();
}

// ============================================================================
// Per-vector quantize / dequantize
// ============================================================================

// Searchsorted: find insertion point for val in sorted array boundaries[0..n-1]
static inline uint8_t searchsorted(const float * boundaries, uint32_t n, float val) {
    uint32_t lo = 0, hi = n;
    while (lo < hi) {
        uint32_t mid = (lo + hi) / 2;
        if (boundaries[mid] < val) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    return (uint8_t)lo;
}

// Pack 3-bit indices: 8 indices → 3 bytes
static void pack_3bit(const uint8_t * indices, uint32_t n, uint8_t * packed) {
    // Pack groups of 8 indices into 3 bytes (24 bits)
    uint32_t full_groups = n / 8;
    uint32_t remainder = n % 8;

    for (uint32_t g = 0; g < full_groups; ++g) {
        const uint8_t * src = indices + g * 8;
        uint32_t bits = 0;
        for (int i = 7; i >= 0; --i) {
            bits = (bits << 3) | (src[i] & 0x7);
        }
        packed[g * 3 + 0] = (uint8_t)(bits & 0xFF);
        packed[g * 3 + 1] = (uint8_t)((bits >> 8) & 0xFF);
        packed[g * 3 + 2] = (uint8_t)((bits >> 16) & 0xFF);
    }

    if (remainder > 0) {
        uint32_t bits = 0;
        const uint8_t * src = indices + full_groups * 8;
        for (int i = (int)remainder - 1; i >= 0; --i) {
            bits = (bits << 3) | (src[i] & 0x7);
        }
        uint32_t packed_bytes = (remainder * 3 + 7) / 8;
        uint8_t * dst = packed + full_groups * 3;
        for (uint32_t b = 0; b < packed_bytes; ++b) {
            dst[b] = (uint8_t)((bits >> (b * 8)) & 0xFF);
        }
    }
}

// Unpack 3-bit indices
static void unpack_3bit(const uint8_t * packed, uint32_t n, uint8_t * indices) {
    uint32_t full_groups = n / 8;
    uint32_t remainder = n % 8;

    for (uint32_t g = 0; g < full_groups; ++g) {
        uint32_t bits = packed[g * 3 + 0]
                      | ((uint32_t)packed[g * 3 + 1] << 8)
                      | ((uint32_t)packed[g * 3 + 2] << 16);
        uint8_t * dst = indices + g * 8;
        for (uint32_t i = 0; i < 8; ++i) {
            dst[i] = (uint8_t)(bits & 0x7);
            bits >>= 3;
        }
    }

    if (remainder > 0) {
        uint32_t packed_bytes = (remainder * 3 + 7) / 8;
        uint32_t bits = 0;
        const uint8_t * src = packed + full_groups * 3;
        for (int b = (int)packed_bytes - 1; b >= 0; --b) {
            bits = (bits << 8) | src[b];
        }
        uint8_t * dst = indices + full_groups * 8;
        for (uint32_t i = 0; i < remainder; ++i) {
            dst[i] = (uint8_t)(bits & 0x7);
            bits >>= 3;
        }
    }
}

// Pack 4-bit indices: 2 indices per byte
static void pack_4bit(const uint8_t * indices, uint32_t n, uint8_t * packed) {
    uint32_t pairs = n / 2;
    for (uint32_t i = 0; i < pairs; ++i) {
        packed[i] = (indices[i * 2] & 0xF) | ((indices[i * 2 + 1] & 0xF) << 4);
    }
    if (n % 2) {
        packed[pairs] = indices[n - 1] & 0xF;
    }
}

// Unpack 4-bit indices
static void unpack_4bit(const uint8_t * packed, uint32_t n, uint8_t * indices) {
    uint32_t pairs = n / 2;
    for (uint32_t i = 0; i < pairs; ++i) {
        indices[i * 2]     = packed[i] & 0xF;
        indices[i * 2 + 1] = (packed[i] >> 4) & 0xF;
    }
    if (n % 2) {
        indices[n - 1] = packed[pairs] & 0xF;
    }
}

// Compute packed size in bytes for n elements at given bits
static uint32_t packed_size(uint32_t n, uint8_t bits) {
    if (bits == 3) {
        uint32_t full = (n / 8) * 3;
        uint32_t rem = n % 8;
        return full + (rem > 0 ? (rem * 3 + 7) / 8 : 0);
    }
    if (bits == 4) {
        return (n + 1) / 2;
    }
    return n; // fallback: 1 byte per index
}

// Quantize cell_count vectors of dimension dim from fp16 → compressed indices + norms
static void tq_quantize_vectors(
    const ggml_fp16_t * src, uint32_t cell_count, uint32_t dim,
    uint8_t bits, uint8_t * dst_indices, float * dst_norms)
{
    const float * boundaries = tq_get_boundaries(dim, bits);
    if (!boundaries) return; // unsupported dim/bits combination
    uint32_t n_boundaries = (1u << bits) - 1;
    const tq_rotation & rot = get_rotation(dim, 42);

    std::vector<float> vec(dim);
    std::vector<float> rotated(dim);
    std::vector<uint8_t> indices(dim);

    for (uint32_t c = 0; c < cell_count; ++c) {
        // Convert fp16 → fp32
        const ggml_fp16_t * row = src + c * dim;
        for (uint32_t d = 0; d < dim; ++d) {
            vec[d] = ggml_fp16_to_fp32(row[d]);
        }

        // Compute L2 norm
        float norm = 0.0f;
        for (uint32_t d = 0; d < dim; ++d) {
            norm += vec[d] * vec[d];
        }
        norm = std::sqrt(norm);
        dst_norms[c] = norm;

        // Normalize
        if (norm > 1e-10f) {
            float inv_norm = 1.0f / norm;
            for (uint32_t d = 0; d < dim; ++d) {
                vec[d] *= inv_norm;
            }
        }

        // Rotate: y = x @ Q^T
        rot.rotate_forward(vec.data(), rotated.data());

        // Scalar quantize each coordinate
        for (uint32_t d = 0; d < dim; ++d) {
            indices[d] = searchsorted(boundaries, n_boundaries, rotated[d]);
        }

        // Pack indices
        uint32_t ps = packed_size(dim, bits);
        if (bits == 3) {
            pack_3bit(indices.data(), dim, dst_indices + c * ps);
        } else {
            pack_4bit(indices.data(), dim, dst_indices + c * ps);
        }
    }
}

// Dequantize compressed indices + norms → fp16 vectors
static void tq_dequantize_vectors(
    const uint8_t * src_indices, const float * src_norms,
    uint32_t cell_count, uint32_t dim, uint8_t bits,
    ggml_fp16_t * dst)
{
    const float * centroids = tq_get_centroids(dim, bits);
    if (!centroids) return; // unsupported dim/bits combination
    const tq_rotation & rot = get_rotation(dim, 42);

    std::vector<uint8_t> indices(dim);
    std::vector<float> rotated(dim);
    std::vector<float> vec(dim);

    uint32_t ps = packed_size(dim, bits);

    for (uint32_t c = 0; c < cell_count; ++c) {
        // Unpack indices
        if (bits == 3) {
            unpack_3bit(src_indices + c * ps, dim, indices.data());
        } else {
            unpack_4bit(src_indices + c * ps, dim, indices.data());
        }

        // Centroid lookup
        for (uint32_t d = 0; d < dim; ++d) {
            rotated[d] = centroids[indices[d]];
        }

        // Inverse rotate: y = x @ Q
        rot.rotate_backward(rotated.data(), vec.data());

        // Rescale by norm
        float norm = src_norms[c];
        for (uint32_t d = 0; d < dim; ++d) {
            vec[d] *= norm;
        }

        // Convert fp32 → fp16
        ggml_fp16_t * row = dst + c * dim;
        for (uint32_t d = 0; d < dim; ++d) {
            row[d] = ggml_fp32_to_fp16(vec[d]);
        }
    }
}

// ============================================================================
// Q8 quantization for recurrent state (F32 tensors)
// Per-row affine quantization: val = scale * quant + min
// ============================================================================

struct q8_row_header {
    float scale;
    float min_val;
};

// Quantize F32 rows to Q8 (uint8) with per-row scale+min
static void q8_quantize_rows(
    const float * src, uint32_t n_rows, uint32_t row_dim,
    uint8_t * dst_quant, q8_row_header * dst_headers)
{
    for (uint32_t r = 0; r < n_rows; ++r) {
        const float * row = src + r * row_dim;

        // Find min/max
        float rmin = row[0], rmax = row[0];
        for (uint32_t d = 1; d < row_dim; ++d) {
            if (row[d] < rmin) rmin = row[d];
            if (row[d] > rmax) rmax = row[d];
        }

        float range = rmax - rmin;
        float scale = range > 1e-10f ? range / 255.0f : 0.0f;
        float inv_scale = scale > 1e-10f ? 1.0f / scale : 0.0f;

        dst_headers[r].scale = scale;
        dst_headers[r].min_val = rmin;

        uint8_t * qrow = dst_quant + r * row_dim;
        for (uint32_t d = 0; d < row_dim; ++d) {
            float normalized = (row[d] - rmin) * inv_scale;
            int q = (int)(normalized + 0.5f);
            qrow[d] = (uint8_t)(q < 0 ? 0 : (q > 255 ? 255 : q));
        }
    }
}

// Dequantize Q8 back to F32
static void q8_dequantize_rows(
    const uint8_t * src_quant, const q8_row_header * src_headers,
    uint32_t n_rows, uint32_t row_dim, float * dst)
{
    for (uint32_t r = 0; r < n_rows; ++r) {
        float scale = src_headers[r].scale;
        float min_val = src_headers[r].min_val;
        const uint8_t * qrow = src_quant + r * row_dim;
        float * out = dst + r * row_dim;

        for (uint32_t d = 0; d < row_dim; ++d) {
            out[d] = scale * (float)qrow[d] + min_val;
        }
    }
}

// ============================================================================
// Buffer reader helper
// ============================================================================

struct buf_reader {
    const uint8_t * data;
    size_t size;
    size_t pos = 0;

    bool can_read(size_t n) const { return pos + n <= size; }

    template <typename T>
    bool read(T & val) {
        if (!can_read(sizeof(T))) return false;
        memcpy(&val, data + pos, sizeof(T));
        pos += sizeof(T);
        return true;
    }

    bool skip(size_t n) {
        if (!can_read(n)) return false;
        pos += n;
        return true;
    }

    const uint8_t * ptr() const { return data + pos; }
};

struct buf_writer {
    std::vector<uint8_t> & buf;

    template <typename T>
    void write(const T & val) {
        const uint8_t * p = reinterpret_cast<const uint8_t *>(&val);
        buf.insert(buf.end(), p, p + sizeof(T));
    }

    void write_bytes(const uint8_t * src, size_t n) {
        buf.insert(buf.end(), src, src + n);
    }
};

// ============================================================================
// Compressed format header
// ============================================================================

struct tq_header {
    uint32_t magic       = TURBOQUANT_MAGIC;
    uint32_t version     = TURBOQUANT_VERSION;
    uint64_t orig_size   = 0;  // original uncompressed buffer size
    uint64_t meta_size   = 0;  // bytes of metadata (pass-through verbatim)
    uint8_t  bits_k      = 3;
    uint8_t  bits_v      = 4;
    uint16_t padding     = 0;
    uint32_t n_stream    = 0;  // total streams (to reconstruct trailing empty ones)
    uint32_t n_layer     = 0;
    uint32_t v_trans     = 0;
    uint32_t n_trailing  = 0;  // number of trailing empty streams after the active one
    uint64_t recur_size  = 0;  // original recurrent state size (0 = none)
    uint32_t recur_compressed = 0; // 1 if recurrent state is Q8-compressed, 0 if verbatim
    uint32_t recur_n_layer = 0;   // number of recurrent layers
};

static constexpr size_t TQ_HEADER_SIZE = sizeof(tq_header);

// Per-layer compressed data header
struct tq_layer_header {
    uint32_t dim;        // n_embd_k_gqa or n_embd_v_gqa
    uint32_t cell_count;
    int32_t  orig_type;  // original ggml_type
};

// ============================================================================
// Main compress / decompress
// ============================================================================

bool turboquant_is_compressed(const uint8_t * data, size_t size) {
    if (size < 4) return false;
    uint32_t magic;
    memcpy(&magic, data, sizeof(magic));
    return magic == TURBOQUANT_MAGIC;
}

bool turboquant_compress(
    const uint8_t * src, size_t src_size,
    std::vector<uint8_t> & dst,
    uint8_t bits_k, uint8_t bits_v)
{
    if (!src || src_size < 8) return false;
    if (turboquant_is_compressed(src, src_size)) return false;

    // --- Locate the data section by scanning for its signature ---
    // The metadata format is complex and variable (optional ext fields, variable n_seq_id).
    // Instead of parsing it byte-by-byte, we scan for the data section header:
    //   v_trans (uint32: 0 or 1), n_layer (uint32: 1-50), k_type (int32: GGML_TYPE_F16=1)
    // This 12-byte signature is unique enough to find reliably.

    // First, read n_stream and cell_count
    buf_reader rd{src, src_size};
    uint32_t n_stream;
    if (!rd.read(n_stream)) return false;

    size_t meta_start = rd.pos;
    uint32_t total_cell_count = 0;

    // Read all stream cell counts
    for (uint32_t s = 0; s < n_stream; ++s) {
        uint32_t cell_count;
        if (!rd.read(cell_count)) return false;
        if (cell_count > 0) {
            if (total_cell_count > 0) return false; // multiple active streams
            total_cell_count = cell_count;
        }
    }
    if (total_cell_count == 0) return false;

    // Scan for data section: v_trans (0|1) + n_layer (1-50) + k_type (F16=1) + k_size_row (reasonable)
    uint32_t v_trans = 0, n_layer = 0;
    size_t data_section_start = 0;

    for (size_t probe = rd.pos; probe + 20 <= src_size; probe += 4) {
        uint32_t w0, w1;
        int32_t w2;
        uint64_t w3;
        memcpy(&w0, src + probe, 4);
        memcpy(&w1, src + probe + 4, 4);
        memcpy(&w2, src + probe + 8, 4);
        memcpy(&w3, src + probe + 12, 8);

        // v_trans=0or1, n_layer=1..50, k_type=F16(1), k_size_row matches cell dim
        if ((w0 == 0 || w0 == 1) && w1 >= 1 && w1 <= 50
            && w2 == GGML_TYPE_F16 && (w3 == 1024 || w3 == 512 || w3 == 256)) {
            v_trans = w0;
            n_layer = w1;
            data_section_start = probe;
            break;
        }
    }

    if (data_section_start == 0) {
        // No KV data section found — this might be a PARTIAL_ONLY (recurrent-only) buffer.
        // Format: cell_count(4), per-cell metadata(8*N), s_trans(4), n_layer(4), R/S tensors
        // The first uint32 we read as n_stream is actually cell_count.
        uint32_t rec_cell_count = n_stream; // reinterpret
        size_t rec_meta_inner = (size_t)rec_cell_count * 8;
        size_t rec_data_offset = 4 + rec_meta_inner; // 4 for cell_count

        if (rec_data_offset + 8 <= src_size) {
            uint32_t s_trans_check, n_layer_check;
            memcpy(&s_trans_check, src + rec_data_offset, 4);
            memcpy(&n_layer_check, src + rec_data_offset + 4, 4);

            if (s_trans_check <= 1 && n_layer_check >= 1 && n_layer_check <= 50) {
                // Valid recurrent-only buffer — compress just the recurrent portion
                SRV_WRN("TurboQuant: recurrent-only buffer %zu bytes, cells=%u, n_layer=%u\n",
                        src_size, rec_cell_count, n_layer_check);

                dst.clear();
                dst.reserve(src_size / 3);
                buf_writer wr{dst};

                tq_header hdr;
                hdr.orig_size = src_size;
                hdr.meta_size = 0;
                hdr.bits_k = bits_k;
                hdr.bits_v = bits_v;
                hdr.n_stream = 0; // signal: recurrent-only buffer
                hdr.n_trailing = 0;
                hdr.n_layer = 0;
                hdr.v_trans = 0;
                hdr.recur_size = src_size;
                hdr.recur_compressed = 1;
                hdr.recur_n_layer = n_layer_check;
                wr.write(hdr);

                // Write cell_count + metadata verbatim
                wr.write_bytes(src, 4 + rec_meta_inner);

                // Write s_trans + n_layer
                wr.write(s_trans_check);
                wr.write(n_layer_check);

                // Compress R and S tensors with Q8
                buf_reader rd_rt{src, src_size};
                rd_rt.pos = rec_data_offset + 8;

                // Probe for actual R layer count
                uint32_t n_r_actual = 0;
                {
                    buf_reader probe = rd_rt;
                    for (uint32_t l = 0; l < n_layer_check; ++l) {
                        int32_t t; uint64_t sz;
                        size_t saved = probe.pos;
                        if (!probe.read(t) || !probe.read(sz)) break;
                        if (t != GGML_TYPE_F32 || sz == 0 || sz > 10000000) { probe.pos = saved; break; }
                        if (!probe.skip(rec_cell_count * sz)) { probe.pos = saved; break; }
                        n_r_actual++;
                    }
                }
                wr.write(n_r_actual);

                for (uint32_t l = 0; l < n_r_actual; ++l) {
                    int32_t r_type_i; uint64_t r_size_row;
                    if (!rd_rt.read(r_type_i) || !rd_rt.read(r_size_row)) return false;

                    uint32_t row_dim = (uint32_t)(r_size_row / sizeof(float));
                    tq_layer_header lh;
                    lh.dim = row_dim;
                    lh.cell_count = rec_cell_count;
                    lh.orig_type = r_type_i;
                    wr.write(lh);

                    const float * data = reinterpret_cast<const float *>(rd_rt.ptr());
                    std::vector<q8_row_header> headers(rec_cell_count);
                    std::vector<uint8_t> quant(rec_cell_count * row_dim);
                    q8_quantize_rows(data, rec_cell_count, row_dim, quant.data(), headers.data());
                    wr.write_bytes(reinterpret_cast<const uint8_t *>(headers.data()), headers.size() * sizeof(q8_row_header));
                    wr.write_bytes(quant.data(), quant.size());
                    rd_rt.pos += rec_cell_count * r_size_row;
                }

                // Probe for actual S layer count
                uint32_t n_s_actual = 0;
                {
                    buf_reader probe = rd_rt;
                    for (uint32_t l = 0; l < n_layer_check; ++l) {
                        int32_t t; uint64_t sz;
                        size_t saved = probe.pos;
                        if (!probe.read(t) || !probe.read(sz)) break;
                        if (t != GGML_TYPE_F32 || sz == 0 || sz > 100000000) { probe.pos = saved; break; }
                        if (!probe.skip(rec_cell_count * sz)) { probe.pos = saved; break; }
                        n_s_actual++;
                    }
                }
                wr.write(n_s_actual);

                for (uint32_t l = 0; l < n_s_actual; ++l) {
                    int32_t s_type_i; uint64_t s_size_row;
                    if (!rd_rt.read(s_type_i) || !rd_rt.read(s_size_row)) return false;

                    uint32_t row_dim = (uint32_t)(s_size_row / sizeof(float));
                    tq_layer_header lh;
                    lh.dim = row_dim;
                    lh.cell_count = rec_cell_count;
                    lh.orig_type = s_type_i;
                    wr.write(lh);

                    const float * data = reinterpret_cast<const float *>(rd_rt.ptr());
                    std::vector<q8_row_header> headers(rec_cell_count);
                    std::vector<uint8_t> quant(rec_cell_count * row_dim);
                    q8_quantize_rows(data, rec_cell_count, row_dim, quant.data(), headers.data());
                    wr.write_bytes(reinterpret_cast<const uint8_t *>(headers.data()), headers.size() * sizeof(q8_row_header));
                    wr.write_bytes(quant.data(), quant.size());
                    rd_rt.pos += rec_cell_count * s_size_row;
                }

                return true;
            }
        }

        SRV_WRN("TurboQuant: unrecognized buffer format (%zu bytes), skipping\n", src_size);
        return false;
    }

    size_t meta_size = data_section_start - meta_start;

    // Parse from data section to find KV tensor regions and recurrent state boundary
    buf_reader rd2{src, src_size};
    rd2.pos = data_section_start + 8; // skip v_trans + n_layer

    // Skip K+V to find recurrent state
    buf_reader rd_skip = rd2;
    for (uint32_t l = 0; l < n_layer; ++l) {
        int32_t t; uint64_t sz;
        if (!rd_skip.read(t) || !rd_skip.read(sz)) return false;
        if (!rd_skip.skip(total_cell_count * sz)) return false;
    }
    if (v_trans == 0) {
        for (uint32_t l = 0; l < n_layer; ++l) {
            int32_t t; uint64_t sz;
            if (!rd_skip.read(t) || !rd_skip.read(sz)) return false;
            if (!rd_skip.skip(total_cell_count * sz)) return false;
        }
    } else {
        for (uint32_t l = 0; l < n_layer; ++l) {
            int32_t t; uint32_t el, dim;
            if (!rd_skip.read(t) || !rd_skip.read(el) || !rd_skip.read(dim)) return false;
            if (!rd_skip.skip((size_t)dim * total_cell_count * el)) return false;
        }
    }
    size_t recur_start = rd_skip.pos;
    size_t recur_size = src_size - recur_start;

    SRV_WRN("TurboQuant: buf=%zu, cells=%u, v_trans=%u, n_layer=%u, meta=%zu, data@%zu, recur=%zu\n",
            src_size, total_cell_count, v_trans, n_layer, meta_size, data_section_start, recur_size);

    // --- Compress K tensors ---
    struct layer_data {
        int32_t  type;
        uint32_t dim;        // n_embd_gqa (elements per cell)
        uint32_t cell_count;
        const uint8_t * raw; // pointer into src buffer
        size_t raw_size;
    };
    std::vector<layer_data> k_layers(n_layer);
    std::vector<layer_data> v_layers;

    for (uint32_t l = 0; l < n_layer; ++l) {
        int32_t k_type_i;
        uint64_t k_size_row;
        if (!rd2.read(k_type_i)) return false;
        if (!rd2.read(k_size_row)) return false;

        // Only compress F16 data
        if (k_type_i != GGML_TYPE_F16) return false;

        uint32_t k_dim = (uint32_t)(k_size_row / sizeof(ggml_fp16_t));
        size_t tensor_size = total_cell_count * k_size_row;

        if (!rd2.can_read(tensor_size)) return false;
        k_layers[l] = {k_type_i, k_dim, total_cell_count, rd2.ptr(), tensor_size};
        rd2.pos += tensor_size;
    }

    // --- Parse V tensors ---
    if (v_trans == 0) {
        v_layers.resize(n_layer);
        for (uint32_t l = 0; l < n_layer; ++l) {
            int32_t v_type_i;
            uint64_t v_size_row;
            if (!rd2.read(v_type_i)) return false;
            if (!rd2.read(v_size_row)) return false;

            if (v_type_i != GGML_TYPE_F16) return false;

            uint32_t v_dim = (uint32_t)(v_size_row / sizeof(ggml_fp16_t));
            size_t tensor_size = total_cell_count * v_size_row;

            if (!rd2.can_read(tensor_size)) return false;
            v_layers[l] = {v_type_i, v_dim, total_cell_count, rd2.ptr(), tensor_size};
            rd2.pos += tensor_size;
        }
    } else {
        // Transposed V: data is stored as n_embd_v_gqa rows of cell_count elements each.
        v_layers.resize(n_layer);
        for (uint32_t l = 0; l < n_layer; ++l) {
            int32_t v_type_i;
            uint32_t v_size_el;
            uint32_t n_embd_v_gqa;
            if (!rd2.read(v_type_i)) return false;
            if (!rd2.read(v_size_el)) return false;
            if (!rd2.read(n_embd_v_gqa)) return false;

            if (v_type_i != GGML_TYPE_F16) return false;

            size_t tensor_size = (size_t)n_embd_v_gqa * total_cell_count * v_size_el;

            if (!rd2.can_read(tensor_size)) return false;
            v_layers[l] = {v_type_i, n_embd_v_gqa, total_cell_count, rd2.ptr(), tensor_size};
            rd2.pos += tensor_size;
        }
    }

    // --- Write compressed format ---
    dst.clear();
    dst.reserve(src_size / 3); // rough estimate

    buf_writer wr{dst};

    tq_header hdr;
    hdr.orig_size   = src_size;
    hdr.meta_size   = meta_size;
    hdr.bits_k      = bits_k;
    hdr.n_stream    = n_stream;
    hdr.n_trailing  = 0; // trailing empty streams are included in meta passthrough
    hdr.bits_v     = bits_v;
    hdr.n_layer    = n_layer;
    hdr.v_trans    = v_trans;
    hdr.recur_size = recur_size;
    wr.write(hdr);

    // Write n_stream + metadata verbatim
    wr.write(n_stream);
    wr.write_bytes(src + meta_start, meta_size);

    // Compress and write K tensors
    for (uint32_t l = 0; l < n_layer; ++l) {
        const auto & kl = k_layers[l];

        tq_layer_header lh;
        lh.dim = kl.dim;
        lh.cell_count = kl.cell_count;
        lh.orig_type = kl.type;
        wr.write(lh);

        // Allocate compressed storage
        uint32_t ps = packed_size(kl.dim, bits_k);
        std::vector<float> norms(kl.cell_count);
        std::vector<uint8_t> indices(kl.cell_count * ps);

        tq_quantize_vectors(
            reinterpret_cast<const ggml_fp16_t *>(kl.raw),
            kl.cell_count, kl.dim, bits_k,
            indices.data(), norms.data());

        wr.write_bytes(reinterpret_cast<const uint8_t *>(norms.data()), norms.size() * sizeof(float));
        wr.write_bytes(indices.data(), indices.size());
    }

    // Compress and write V tensors
    for (uint32_t l = 0; l < n_layer; ++l) {
        const auto & vl = v_layers[l];

        tq_layer_header lh;
        lh.dim = vl.dim;
        lh.cell_count = vl.cell_count;
        lh.orig_type = vl.type;
        wr.write(lh);

        uint32_t ps = packed_size(vl.dim, bits_v);
        std::vector<float> norms(vl.cell_count);
        std::vector<uint8_t> indices(vl.cell_count * ps);

        if (v_trans == 0) {
            // Non-transposed: data is already (cell_count, dim) row-major
            tq_quantize_vectors(
                reinterpret_cast<const ggml_fp16_t *>(vl.raw),
                vl.cell_count, vl.dim, bits_v,
                indices.data(), norms.data());
        } else {
            // Transposed: data is (dim, cell_count) — gather into row-major (cell_count, dim)
            std::vector<ggml_fp16_t> gathered(vl.cell_count * vl.dim);
            const ggml_fp16_t * v_data = reinterpret_cast<const ggml_fp16_t *>(vl.raw);
            for (uint32_t d = 0; d < vl.dim; ++d) {
                for (uint32_t c = 0; c < vl.cell_count; ++c) {
                    gathered[c * vl.dim + d] = v_data[d * vl.cell_count + c];
                }
            }
            tq_quantize_vectors(
                gathered.data(), vl.cell_count, vl.dim, bits_v,
                indices.data(), norms.data());
        }

        wr.write_bytes(reinterpret_cast<const uint8_t *>(norms.data()), norms.size() * sizeof(float));
        wr.write_bytes(indices.data(), indices.size());
    }

    // Compress recurrent state (R and S tensors are F32 — Q8 quantization)
    if (recur_size > 0) {
        buf_reader rd_rec{src, src_size};
        rd_rec.pos = recur_start;

        // Recurrent format: cell_count, metadata, then data section
        // Data section: s_trans(4), n_layer(4), then per-layer R tensors, then per-layer S tensors
        // We need to scan for the data section just like KV
        uint32_t rec_cell_count;
        if (!rd_rec.read(rec_cell_count)) goto recur_verbatim;

        if (rec_cell_count == 0) goto recur_verbatim;

        // For seq_id != -1 (our case), recurrent metadata per cell is exactly 8 bytes:
        //   pos (int32 = 4 bytes) + n_seq_id (uint32 = 4 bytes, always 0)
        // So the data section starts at a deterministic offset.
        size_t rec_meta_size_inner = (size_t)rec_cell_count * 8; // per-cell metadata
        size_t rec_data_start = rd_rec.pos + rec_meta_size_inner;

        if (rec_data_start + 8 > src_size) goto recur_verbatim;

        uint32_t rec_s_trans, rec_n_layer;
        memcpy(&rec_s_trans, src + rec_data_start, 4);
        memcpy(&rec_n_layer, src + rec_data_start + 4, 4);

        // Sanity check
        if (rec_s_trans > 1 || rec_n_layer == 0 || rec_n_layer > 50) {
            SRV_WRN("TurboQuant: recurrent data header invalid (s_trans=%u, n_layer=%u), falling back\n",
                    rec_s_trans, rec_n_layer);
            goto recur_verbatim;
        }

        // Write recurrent metadata verbatim (cell_count + per-cell metadata)
        size_t rec_meta_total = 4 + rec_meta_size_inner; // cell_count(4) + per-cell(8*N)
        wr.write_bytes(src + recur_start, rec_meta_total);

        // Write recurrent data header
        wr.write(rec_s_trans);
        wr.write(rec_n_layer);

        hdr.recur_compressed = 1;
        hdr.recur_n_layer = rec_n_layer;

        // Compress R and S tensors with Q8
        // The write code skips null layers (attention-only layers have no recurrent state),
        // so we probe forward to count actual R entries, then S entries.
        buf_reader rd_rt{src, src_size};
        rd_rt.pos = rec_data_start + 8; // skip s_trans + n_layer

        // Count actual R layer entries by probing
        uint32_t n_r_actual = 0;
        {
            buf_reader probe = rd_rt;
            for (uint32_t l = 0; l < rec_n_layer; ++l) {
                int32_t t; uint64_t sz;
                size_t saved = probe.pos;
                if (!probe.read(t) || !probe.read(sz)) break;
                if (t != GGML_TYPE_F32 || sz == 0 || sz > 10000000) { probe.pos = saved; break; }
                if (!probe.skip(rec_cell_count * sz)) { probe.pos = saved; break; }
                n_r_actual++;
            }
        }

        // Write actual R layer count so decompressor knows
        wr.write(n_r_actual);

        // R tensors
        for (uint32_t l = 0; l < n_r_actual; ++l) {
            int32_t r_type_i;
            uint64_t r_size_row;
            if (!rd_rt.read(r_type_i)) goto recur_verbatim;
            if (!rd_rt.read(r_size_row)) goto recur_verbatim;

            size_t r_data_size = rec_cell_count * r_size_row;
            if (!rd_rt.can_read(r_data_size)) goto recur_verbatim;

            if (r_type_i == GGML_TYPE_F32) {
                uint32_t row_dim = (uint32_t)(r_size_row / sizeof(float));

                tq_layer_header lh;
                lh.dim = row_dim;
                lh.cell_count = rec_cell_count;
                lh.orig_type = r_type_i;
                wr.write(lh);

                const float * r_data = reinterpret_cast<const float *>(rd_rt.ptr());
                std::vector<q8_row_header> headers(rec_cell_count);
                std::vector<uint8_t> quant(rec_cell_count * row_dim);

                q8_quantize_rows(r_data, rec_cell_count, row_dim, quant.data(), headers.data());

                wr.write_bytes(reinterpret_cast<const uint8_t *>(headers.data()), headers.size() * sizeof(q8_row_header));
                wr.write_bytes(quant.data(), quant.size());
            } else {
                // Unsupported type — write layer header + raw data
                tq_layer_header lh;
                lh.dim = 0; // signal: raw passthrough
                lh.cell_count = rec_cell_count;
                lh.orig_type = r_type_i;
                wr.write(lh);
                wr.write(r_size_row);
                wr.write_bytes(rd_rt.ptr(), r_data_size);
            }
            rd_rt.pos += r_data_size;
        }

        // Count actual S layer entries
        uint32_t n_s_actual = 0;
        {
            buf_reader probe = rd_rt;
            for (uint32_t l = 0; l < rec_n_layer; ++l) {
                int32_t t; uint64_t sz;
                size_t saved = probe.pos;
                if (!probe.read(t) || !probe.read(sz)) break;
                if (t != GGML_TYPE_F32 || sz == 0 || sz > 100000000) { probe.pos = saved; break; }
                if (!probe.skip(rec_cell_count * sz)) { probe.pos = saved; break; }
                n_s_actual++;
            }
        }
        wr.write(n_s_actual);

        // S tensors
        for (uint32_t l = 0; l < n_s_actual; ++l) {
            int32_t s_type_i;
            uint64_t s_size_row;
            if (!rd_rt.read(s_type_i)) goto recur_verbatim;
            if (!rd_rt.read(s_size_row)) goto recur_verbatim;

            size_t s_data_size = rec_cell_count * s_size_row;
            if (!rd_rt.can_read(s_data_size)) goto recur_verbatim;

            if (s_type_i == GGML_TYPE_F32) {
                uint32_t row_dim = (uint32_t)(s_size_row / sizeof(float));

                tq_layer_header lh;
                lh.dim = row_dim;
                lh.cell_count = rec_cell_count;
                lh.orig_type = s_type_i;
                wr.write(lh);

                const float * s_data = reinterpret_cast<const float *>(rd_rt.ptr());
                std::vector<q8_row_header> headers(rec_cell_count);
                std::vector<uint8_t> quant(rec_cell_count * row_dim);

                q8_quantize_rows(s_data, rec_cell_count, row_dim, quant.data(), headers.data());

                wr.write_bytes(reinterpret_cast<const uint8_t *>(headers.data()), headers.size() * sizeof(q8_row_header));
                wr.write_bytes(quant.data(), quant.size());
            } else {
                tq_layer_header lh;
                lh.dim = 0;
                lh.cell_count = rec_cell_count;
                lh.orig_type = s_type_i;
                wr.write(lh);
                wr.write(s_size_row);
                wr.write_bytes(rd_rt.ptr(), s_data_size);
            }
            rd_rt.pos += s_data_size;
        }

        // Update header with actual recur_compressed flag
        // (header was already written — need to patch it)
        memcpy(dst.data() + offsetof(tq_header, recur_compressed), &hdr.recur_compressed, sizeof(hdr.recur_compressed));
        memcpy(dst.data() + offsetof(tq_header, recur_n_layer), &hdr.recur_n_layer, sizeof(hdr.recur_n_layer));

        goto recur_done;
    }

recur_verbatim:
    // Fallback: write recurrent state as-is
    if (recur_size > 0) {
        hdr.recur_compressed = 0;
        wr.write_bytes(src + recur_start, recur_size);
    }

recur_done:
    return true;
}

bool turboquant_decompress(
    const uint8_t * src, size_t src_size,
    std::vector<uint8_t> & dst)
{
    if (!turboquant_is_compressed(src, src_size)) return false;

    buf_reader rd{src, src_size};

    tq_header hdr;
    if (!rd.read(hdr)) return false;
    if (hdr.version != TURBOQUANT_VERSION) return false;

    // Allocate output at original size
    dst.resize(hdr.orig_size);
    buf_writer wr{dst};
    dst.clear(); // buf_writer appends, so start empty

    if (hdr.n_stream == 0) {
        // Recurrent-only buffer (PARTIAL_ONLY checkpoint)
        // Format in compressed stream: [cell_count + metadata verbatim][s_trans][n_layer][n_r_actual][R layers][n_s_actual][S layers]
        // Reconstruct: [cell_count + metadata][s_trans][n_layer][R layers raw][S layers raw]

        // Read cell_count + metadata verbatim
        uint32_t rec_cell_count;
        if (!rd.read(rec_cell_count)) return false;
        wr.write(rec_cell_count);
        size_t rec_meta_inner = (size_t)rec_cell_count * 8;
        if (!rd.can_read(rec_meta_inner)) return false;
        wr.write_bytes(rd.ptr(), rec_meta_inner);
        rd.pos += rec_meta_inner;

        uint32_t s_trans, n_rec_layer;
        if (!rd.read(s_trans)) return false;
        if (!rd.read(n_rec_layer)) return false;
        wr.write(s_trans);
        wr.write(n_rec_layer);

        // Decompress R tensors
        uint32_t n_r_actual;
        if (!rd.read(n_r_actual)) return false;
        for (uint32_t l = 0; l < n_r_actual; ++l) {
            tq_layer_header lh;
            if (!rd.read(lh)) return false;
            size_t headers_size = lh.cell_count * sizeof(q8_row_header);
            size_t quant_size = (size_t)lh.cell_count * lh.dim;
            if (!rd.can_read(headers_size + quant_size)) return false;
            const q8_row_header * headers = reinterpret_cast<const q8_row_header *>(rd.ptr());
            rd.pos += headers_size;
            const uint8_t * quant = rd.ptr();
            rd.pos += quant_size;

            std::vector<float> f32_data(lh.cell_count * lh.dim);
            q8_dequantize_rows(quant, headers, lh.cell_count, lh.dim, f32_data.data());

            int32_t type_i = lh.orig_type;
            uint64_t row_size = (uint64_t)lh.dim * sizeof(float);
            wr.write(type_i);
            wr.write(row_size);
            wr.write_bytes(reinterpret_cast<const uint8_t *>(f32_data.data()), f32_data.size() * sizeof(float));
        }

        // Decompress S tensors
        uint32_t n_s_actual;
        if (!rd.read(n_s_actual)) return false;
        for (uint32_t l = 0; l < n_s_actual; ++l) {
            tq_layer_header lh;
            if (!rd.read(lh)) return false;
            size_t headers_size = lh.cell_count * sizeof(q8_row_header);
            size_t quant_size = (size_t)lh.cell_count * lh.dim;
            if (!rd.can_read(headers_size + quant_size)) return false;
            const q8_row_header * headers = reinterpret_cast<const q8_row_header *>(rd.ptr());
            rd.pos += headers_size;
            const uint8_t * quant = rd.ptr();
            rd.pos += quant_size;

            std::vector<float> f32_data(lh.cell_count * lh.dim);
            q8_dequantize_rows(quant, headers, lh.cell_count, lh.dim, f32_data.data());

            int32_t type_i = lh.orig_type;
            uint64_t row_size = (uint64_t)lh.dim * sizeof(float);
            wr.write(type_i);
            wr.write(row_size);
            wr.write_bytes(reinterpret_cast<const uint8_t *>(f32_data.data()), f32_data.size() * sizeof(float));
        }

        return true;
    }

    // Full KV+recurrent buffer
    // Read and write n_stream + metadata verbatim
    uint32_t n_stream;
    if (!rd.read(n_stream)) return false;
    wr.write(n_stream);
    if (!rd.can_read(hdr.meta_size)) return false;
    wr.write_bytes(rd.ptr(), hdr.meta_size);
    rd.pos += hdr.meta_size;

    // Write data header
    wr.write(hdr.v_trans);
    wr.write(hdr.n_layer);

    // Decompress K tensors
    for (uint32_t l = 0; l < hdr.n_layer; ++l) {
        tq_layer_header lh;
        if (!rd.read(lh)) return false;

        // Write original K header
        int32_t k_type_i = lh.orig_type;
        uint64_t k_size_row = (uint64_t)lh.dim * sizeof(ggml_fp16_t);
        wr.write(k_type_i);
        wr.write(k_size_row);

        // Read compressed data
        size_t norms_size = lh.cell_count * sizeof(float);
        uint32_t ps = packed_size(lh.dim, hdr.bits_k);
        size_t indices_size = (size_t)lh.cell_count * ps;

        if (!rd.can_read(norms_size + indices_size)) return false;
        const float * norms = reinterpret_cast<const float *>(rd.ptr());
        rd.pos += norms_size;
        const uint8_t * indices = rd.ptr();
        rd.pos += indices_size;

        // Dequantize
        std::vector<ggml_fp16_t> fp16_data(lh.cell_count * lh.dim);
        tq_dequantize_vectors(indices, norms, lh.cell_count, lh.dim, hdr.bits_k, fp16_data.data());

        wr.write_bytes(reinterpret_cast<const uint8_t *>(fp16_data.data()),
                       fp16_data.size() * sizeof(ggml_fp16_t));
    }

    // Decompress V tensors
    for (uint32_t l = 0; l < hdr.n_layer; ++l) {
        tq_layer_header lh;
        if (!rd.read(lh)) return false;

        size_t norms_size = lh.cell_count * sizeof(float);
        uint32_t ps = packed_size(lh.dim, hdr.bits_v);
        size_t indices_size = (size_t)lh.cell_count * ps;

        if (!rd.can_read(norms_size + indices_size)) return false;
        const float * norms = reinterpret_cast<const float *>(rd.ptr());
        rd.pos += norms_size;
        const uint8_t * indices = rd.ptr();
        rd.pos += indices_size;

        // Dequantize to row-major (cell_count, dim)
        std::vector<ggml_fp16_t> fp16_data(lh.cell_count * lh.dim);
        tq_dequantize_vectors(indices, norms, lh.cell_count, lh.dim, hdr.bits_v, fp16_data.data());

        if (hdr.v_trans == 0) {
            // Non-transposed: write type + row_size header, then contiguous data
            int32_t v_type_i = lh.orig_type;
            uint64_t v_size_row = (uint64_t)lh.dim * sizeof(ggml_fp16_t);
            wr.write(v_type_i);
            wr.write(v_size_row);

            wr.write_bytes(reinterpret_cast<const uint8_t *>(fp16_data.data()),
                           fp16_data.size() * sizeof(ggml_fp16_t));
        } else {
            // Transposed: write type + el_size + n_embd_v_gqa header,
            // then scatter (cell_count, dim) back to (dim, cell_count)
            int32_t v_type_i = lh.orig_type;
            uint32_t v_size_el = (uint32_t)sizeof(ggml_fp16_t);
            uint32_t n_embd_v_gqa = lh.dim;
            wr.write(v_type_i);
            wr.write(v_size_el);
            wr.write(n_embd_v_gqa);

            // Scatter: for each dimension d, write cell_count elements
            std::vector<ggml_fp16_t> transposed(lh.cell_count * lh.dim);
            for (uint32_t d = 0; d < lh.dim; ++d) {
                for (uint32_t c = 0; c < lh.cell_count; ++c) {
                    transposed[d * lh.cell_count + c] = fp16_data[c * lh.dim + d];
                }
            }
            wr.write_bytes(reinterpret_cast<const uint8_t *>(transposed.data()),
                           transposed.size() * sizeof(ggml_fp16_t));
        }
    }

    // Write trailing empty stream cell_counts (uint32_t = 0 each)
    for (uint32_t t = 0; t < hdr.n_trailing; ++t) {
        uint32_t zero = 0;
        wr.write(zero);
    }

    // Decompress recurrent state
    if (hdr.recur_size > 0 && hdr.recur_compressed == 0) {
        // Verbatim passthrough
        if (!rd.can_read(hdr.recur_size)) return false;
        wr.write_bytes(rd.ptr(), hdr.recur_size);
        rd.pos += hdr.recur_size;
    } else if (hdr.recur_size > 0 && hdr.recur_compressed == 1) {
        // Q8 compressed recurrent state
        // Read recurrent metadata verbatim (cell_count + per-cell metadata)
        // The metadata was written before the data section in compress
        // We need to figure out how much metadata there is — it starts with cell_count
        // and ends at the s_trans + n_layer header we wrote.

        // Read the recurrent metadata that was written verbatim
        // (everything up to s_trans + n_layer which we wrote explicitly)
        // The compress wrote: [rec_meta_verbatim][s_trans][n_layer][compressed R/S layers]
        // rec_meta_verbatim = bytes from recur_start to rec_data_start in original

        // We need to read the verbatim metadata first, then s_trans + n_layer,
        // then decompress the R and S layers

        // Read verbatim metadata (everything until we hit s_trans + n_layer)
        // Actually, the compress function wrote:
        //   wr.write_bytes(src + recur_start, rec_meta_size);  // verbatim meta
        //   wr.write(rec_s_trans);
        //   wr.write(rec_n_layer);
        //   [compressed layers]

        // For decompression, we need to pass through the metadata and reconstruct the data.
        // The metadata includes cell_count + per-cell pos/n_seq_id data.
        // We don't know its exact size, but we DO know n_layer from the header.

        // Read cell_count first to figure out how to write it
        // Actually, the verbatim metadata IS already in the compressed stream.
        // We just need to copy it through and then decompress the layers.

        // Read until we find s_trans(0) + n_layer pattern
        // Actually we stored rec_n_layer in the header, and the compressed data
        // has the metadata followed by s_trans + n_layer + compressed layers.

        // The structure in compressed stream is:
        //   [verbatim_recur_meta][s_trans=0][n_layer=N][layer_header+Q8_data]*N*2

        // Read the verbatim recurrent metadata: cell_count(4) + per-cell(8*N)
        uint32_t rec_cell_count;
        if (!rd.read(rec_cell_count)) return false;
        wr.write(rec_cell_count);

        // Per-cell metadata: 8 bytes each (pos + n_seq_id=0)
        size_t rec_meta_inner = (size_t)rec_cell_count * 8;
        if (!rd.can_read(rec_meta_inner)) return false;
        wr.write_bytes(rd.ptr(), rec_meta_inner);
        rd.pos += rec_meta_inner;

        // Read s_trans + n_layer
        uint32_t s_trans, n_rec_layer;
        if (!rd.read(s_trans)) return false;
        if (!rd.read(n_rec_layer)) return false;

        wr.write(s_trans);
        wr.write(n_rec_layer);

        // Read actual R and S layer counts (written by compressor)
        uint32_t n_r_actual, n_s_actual;
        if (!rd.read(n_r_actual)) return false;

        // Decompress R tensors
        for (uint32_t l = 0; l < n_r_actual; ++l) {
            tq_layer_header lh;
            if (!rd.read(lh)) return false;

            if (lh.dim == 0) {
                // Raw passthrough
                uint64_t orig_row_size;
                if (!rd.read(orig_row_size)) return false;
                int32_t type_i = lh.orig_type;
                wr.write(type_i);
                wr.write(orig_row_size);
                size_t data_size = lh.cell_count * orig_row_size;
                if (!rd.can_read(data_size)) return false;
                wr.write_bytes(rd.ptr(), data_size);
                rd.pos += data_size;
            } else {
                // Q8 compressed
                size_t headers_size = lh.cell_count * sizeof(q8_row_header);
                size_t quant_size = (size_t)lh.cell_count * lh.dim;

                if (!rd.can_read(headers_size + quant_size)) return false;
                const q8_row_header * headers = reinterpret_cast<const q8_row_header *>(rd.ptr());
                rd.pos += headers_size;
                const uint8_t * quant = rd.ptr();
                rd.pos += quant_size;

                std::vector<float> f32_data(lh.cell_count * lh.dim);
                q8_dequantize_rows(quant, headers, lh.cell_count, lh.dim, f32_data.data());

                int32_t type_i = lh.orig_type;
                uint64_t row_size = (uint64_t)lh.dim * sizeof(float);
                wr.write(type_i);
                wr.write(row_size);
                wr.write_bytes(reinterpret_cast<const uint8_t *>(f32_data.data()),
                               f32_data.size() * sizeof(float));
            }
        }

        // Decompress S tensors
        if (!rd.read(n_s_actual)) return false;
        for (uint32_t l = 0; l < n_s_actual; ++l) {
            tq_layer_header lh;
            if (!rd.read(lh)) return false;

            if (lh.dim == 0) {
                uint64_t orig_row_size;
                if (!rd.read(orig_row_size)) return false;
                int32_t type_i = lh.orig_type;
                wr.write(type_i);
                wr.write(orig_row_size);
                size_t data_size = lh.cell_count * orig_row_size;
                if (!rd.can_read(data_size)) return false;
                wr.write_bytes(rd.ptr(), data_size);
                rd.pos += data_size;
            } else {
                size_t headers_size = lh.cell_count * sizeof(q8_row_header);
                size_t quant_size = (size_t)lh.cell_count * lh.dim;

                if (!rd.can_read(headers_size + quant_size)) return false;
                const q8_row_header * headers = reinterpret_cast<const q8_row_header *>(rd.ptr());
                rd.pos += headers_size;
                const uint8_t * quant = rd.ptr();
                rd.pos += quant_size;

                std::vector<float> f32_data(lh.cell_count * lh.dim);
                q8_dequantize_rows(quant, headers, lh.cell_count, lh.dim, f32_data.data());

                int32_t type_i = lh.orig_type;
                uint64_t row_size = (uint64_t)lh.dim * sizeof(float);
                wr.write(type_i);
                wr.write(row_size);
                wr.write_bytes(reinterpret_cast<const uint8_t *>(f32_data.data()),
                               f32_data.size() * sizeof(float));
            }
        }
    }

    return true;
}
